### PR TITLE
[NCL-6870] handle build-metrics duplication

### PR DESCRIPTION
**Pull request by michalovjan**

### CODE REVIEW

**Comment by thescouser89** [comment]
I think change looks good. I'm unsure if `@Transactional` works on those methods, but if it works it works :)

**Review by vibe13 — CHANGES_REQUESTED** [review]
It looks good @michalovjan ! (I have the same reservation about `@Transactional` with `@Incoming`, but let's see!).
I would ask you to change the unique constraint though, to mimic what I have been doing with my clean duplicates SQL script: the duplication happens on `buildid, buildstage, duration, timestamp`. At the moment I am not considering processcontextvariant.
Thanks!!

**Comment by michalovjan** [comment]
@vibe13 @thescouser89  Thanks for feedback guys!! :)

1. @Transactional: I've manually debugged the code to see whether it is within a transactional context and it is! Additionally, you can see a simillar example in the quarkus guide :) [1]
2. UniqueConstraint: I'll change that right away!
3. TestFailing: Can we update our jenkins to use latest maven version? I have a gut feeling it might be because of that.

[1] https://quarkus.io/guides/kafka#persisting-kafka-messages-with-hibernate-with-panache

**Comment by vibe13** [comment]
Perfect Jan, thanks for all the fixes!!

**Review by vibe13 — APPROVED** [review]

**Pull request merged**
